version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=8080
      - DB_USER=root
      - DB_PASSWORD=@MniSQL2024
      - DB_NAME=mydatabase

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: users
    ports:
      - "8080:8080" 
