version: '3.8'

services:
  app:
    image: node:14-alpine
    container_name: node_app
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
    command: ["node", "app.js"]
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./data:/root/db
    command: sqlite3 /root/db/app.db
    restart: unless-stopped

volumes:
  node_modules:

networks:
  default:
    driver: bridge
